"""
Import a Business Central "Table Information" Excel export as a monthly snapshot.

Usage:
    python scripts/import_month.py "<path to Table Information .xlsx>" 2026-10

What it does:
  1. Reads every row of the export (Company Name, Table Name, Table No., No. of Records ...).
  2. Keeps every table that has at least one record, per company.
  3. Writes src/data/months/<YYYY-MM>/snapshot.json
  4. Creates src/data/months/<YYYY-MM>/notes.json (copied from the previous month) if missing,
     so you only have to edit project statuses / highlights.
  5. Adds any company it has not seen before to src/data/companies.json.
  6. Regenerates src/data/registry.ts so the dashboard picks the new month up.

Requires: pip install openpyxl
"""

import json
import re
import shutil
import sys
from datetime import date
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data"
MONTHS = DATA / "months"
COMPANIES = DATA / "companies.json"
REGISTRY = DATA / "registry.ts"

REQUIRED = ["Company Name", "Table Name", "Table No.", "No. of Records"]


def slugify(name: str) -> str:
    s = name.lower().replace("&", " ")
    s = re.sub(r"\b(ltd|inc|limited)\b\.?", " ", s)
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


def read_export(path: Path) -> dict:
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    ws = wb.worksheets[0]
    rows = ws.iter_rows(values_only=True)
    header = [str(h).strip() if h is not None else "" for h in next(rows)]
    missing = [c for c in REQUIRED if c not in header]
    if missing:
        sys.exit(f"Export is missing columns: {missing}. Found: {header}")
    idx = {c: header.index(c) for c in header}
    size_col = idx.get("Size (KB)")

    companies: dict[str, dict] = {}
    for r in rows:
        company = (r[idx["Company Name"]] or "").strip()
        if not company:
            continue  # tenant-wide system tables, not company data
        records = int(r[idx["No. of Records"]] or 0)
        c = companies.setdefault(company, {"bcName": company, "tablesInBc": 0, "sizeKb": 0, "tables": []})
        c["tablesInBc"] += 1
        if size_col is not None:
            c["sizeKb"] += int(r[size_col] or 0)
        if records > 0:
            c["tables"].append({
                "no": int(r[idx["Table No."]]),
                "name": str(r[idx["Table Name"]]).strip(),
                "records": records,
            })
    for c in companies.values():
        c["tables"].sort(key=lambda t: -t["records"])
    return companies


def update_companies(found: dict) -> None:
    known = json.loads(COMPANIES.read_text(encoding="utf-8")) if COMPANIES.exists() else []
    names = {c["bcName"] for c in known}
    added = []
    for bc_name in found:
        if bc_name not in names:
            known.append({"bcName": bc_name, "name": bc_name, "slug": slugify(bc_name)})
            added.append(bc_name)
    COMPANIES.write_text(json.dumps(known, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    for a in added:
        print(f"  + new company added to companies.json: {a!r} (edit its display name there if needed)")


def write_registry() -> None:
    months = sorted(p.name for p in MONTHS.iterdir() if (p / "snapshot.json").exists())
    lines = [
        "// AUTO-GENERATED by scripts/import_month.py - do not edit by hand.",
        'import type { MonthData } from "@/lib/types";',
    ]
    for m in months:
        v = m.replace("-", "_")
        lines.append(f'import snapshot_{v} from "./months/{m}/snapshot.json";')
        lines.append(f'import notes_{v} from "./months/{m}/notes.json";')
    lines.append("")
    lines.append("export const MONTHS: MonthData[] = [")
    for m in months:
        v = m.replace("-", "_")
        lines.append(f'  {{ month: "{m}", snapshot: snapshot_{v}, notes: notes_{v} }} as MonthData,')
    lines.append("];")
    REGISTRY.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 3 or not re.fullmatch(r"\d{4}-\d{2}", sys.argv[2]):
        sys.exit(__doc__)
    src, month = Path(sys.argv[1]), sys.argv[2]
    if not src.exists():
        sys.exit(f"File not found: {src}")

    companies = read_export(src)
    out_dir = MONTHS / month
    out_dir.mkdir(parents=True, exist_ok=True)

    snapshot = {
        "month": month,
        "sourceFile": src.name,
        "importedOn": date.today().isoformat(),
        "companies": sorted(companies.values(), key=lambda c: c["bcName"].lower()),
    }
    (out_dir / "snapshot.json").write_text(json.dumps(snapshot, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {out_dir / 'snapshot.json'}  ({len(companies)} companies)")

    notes = out_dir / "notes.json"
    if not notes.exists():
        previous = sorted(p for p in MONTHS.iterdir() if p.name < month and (p / "notes.json").exists())
        if previous:
            shutil.copy(previous[-1] / "notes.json", notes)
            print(f"Copied notes from {previous[-1].name} -> update project statuses in {notes}")
        else:
            notes.write_text(json.dumps({"summary": [], "projects": [], "attention": []}, indent=2) + "\n", encoding="utf-8")
            print(f"Created empty {notes}")

    update_companies(companies)
    write_registry()
    print("Registry updated. Run `npm run build` to check, then push to deploy.")


if __name__ == "__main__":
    main()
