// AUTO-GENERATED by scripts/import_month.py - do not edit by hand.
import type { MonthData } from "@/lib/types";
import snapshot_2026_09 from "./months/2026-09/snapshot.json";
import notes_2026_09 from "./months/2026-09/notes.json";

export const MONTHS: MonthData[] = [
  { month: "2026-09", snapshot: snapshot_2026_09, notes: notes_2026_09 } as MonthData,
];
